import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
 {/* <header className="bg-blue-600 text-white p-4">
          <h1>Welcome to My Website</h1>
        </header> */}
        <main className="bg-gradient-to-br from-[#0a192f] to-[#112240]">{children}</main>
        {/* <footer className="bg-gradient-to-br from-black to-[#112240]
 text-white p-4 mt-8 text-center">
          <p>© 2025 My Website. All rights reserved.</p>
        </footer> */}
      </body>
    </html>
  );
}
